version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: petfriends
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - '5432:5432'