spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/petfriends
        username: postgres
        password: postgres
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    flyway:
        baseline-on-migrate: true
    logging:
        level:
            org.springframework.boot.autoconfigure.flyway: DEBUG
            org.flywaydb.core.internal.sqlscript: DEBUG